steps:
  - name: gcr.io/kaniko-project/executor:v1.6.0-debug
    args:
      - --destination=gcr.io/$PROJECT_ID/xerox:$BRANCH_NAME
      - --destination=gcr.io/$PROJECT_ID/xerox:$COMMIT_SHA
      - --cache=true
